<?php
    echo "
    <footer>\n
        <div class = \"footer1\">\n
            <a class = \"footer\">Member:</a>\n
            <br>
            <a class = \"footer\" href=\"mailto:103487949@student.swin.edu.au\">103487949 - Xuan Dat Le</a>\n
            <br>
            <a class = \"footer\" href=\"mailto:103793756@student.swin.edu.au\">103793756 - Samer</a>\n
            <br>
            <a class = \"footer\" href=\"mailto:103827804@student.swin.edu.au\">103827804 - The Son Ngo</a>\n
            <br>
            <a class = \"footer\" href=\"mailto:104048305@student.swin.edu.au\">104048305 - Tuan Hung Nguyen</a>\n
            <br>
            <a class = \"footer\" href=\"mailto:103800504@student.swin.edu.au\">103800504 - Nguyen Khanh Nguyen</a>\n
            <br> 
            <br>
            <a>Image from:</a>\n
            <br>
            <a>https://www.dell.com/en-au/shop/dell-laptops/sf/xps-laptops</a> \n
            <br>
            <a>https://www.asus.com/au/</a> \n
            <br>
            <a>https://www.apple.com/au/mac/</a>\n
            <br>
            <a>https://www.hp.com/</a>\n
            <br>
            <a>https://www.lg.com/us/laptops/lg-17Z990-RAAS8U1-ultra-slim-laptop</a>\n
        </div>
    </footer>
    ";
?>