<?php
    echo "
    <header>
        <nav>         
            <p><a class=\"help\" href=\"./enhancements.php\">Enhancement</a></p>\n
            <p><a href=\"manager.php\">Manager</a></p>\n
            <p><a href=\"enquire.php\">Payment</a></p>\n
            <p><a href=\"about.php\">About</a></p>\n
            <p><a href=\"product.php\">Products</a></p>\n
            <p><a href=\"index.php\">Home</a></p>\n
            <p><a href=\"https://youtu.be/XH0w9a2pGkY\">Youtube</a></p>\n
        </nav>
    </header>
    ";
?>